name: Test

on:
	push:
	branches:
		- '**'
	pull_request:
	branches:
		- '**'

jobs:
	test:
	runs-on: ubuntu-latest

	steps:
		- name: Checkout code
		uses: actions/checkout@v4

		- name: Set up Python 3.x
		uses: actions/setup-python@v4
		with:
			python-version: '3.13'

		- name: Cache dependencies
		uses: actions/cache@v4
		with:
			path: ~/.cache/pip
			key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
			restore-keys: |
			${{ runner.os }}-python-

		- name: Install dependencies
		run: |
			python -m pip install --upgrade pip
			pip install -r requirements.txt

		- name: Run tests
		run: |
			python -m unittest discover -s tests
